let API = {
    banner:'/banner',
    Popularsonglist:'/top/playlist',
    hotwall:'/comment/hotwall/list',
    cellphone:'/login/cellphone',
    emailLogin:'/login',
    captchaVerify:'/captcha/sent',
    captchaSent:'/captcha/verify',
    registerCellphone:'/register/cellphone',
    userlevel:'/user/level',
    userDetail:'/user/detail',
    searchDefault:'/search/default',
    searchHot:'/search/hot',
    SearchCloudsearch:'/search',
    CheckMusic:'/check/music',
    songUrl:'/song/url',
    songdetail:'/song/detail',
    userRecord:'/user/record',
    artistList:'/artist/list',
    artistDesc:'/artist/desc',
    artistSongs:'/artist/songs',
    artistTop:'/artist/top/song',
    artistAlbum:'/artist/album',
    artistMv:'/artist/mv',
    detailMv:'/mv/detail',
    mvUrl:'/mv/url',
    detailInfo:'/mv/detail/info',
    commentMV:'/comment/mv',
    topList:'/toplist',
    toplistDetail:'/toplist/detail',
    recommendSongs:'/recommend/songs',
    commentMusic:'/comment/music',
    simiSong:'/simi/song',
}

export default {
    API
}